import './globals.css';
import { Inter } from 'next/font/google';
import Headers from './Headers';
import Footers from './Footers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'ThaiChin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Headers />
        </header>
        <main>{children}</main>
        <footer>
          <Footers />
        </footer>
      </body>
    </html>
  );
}
